# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [36]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [37]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([2,3,4])

# Create a 2-dimensional NumPy array using np.array()

a2 = np.array([[2,3,4],[4,56,4]])
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[2,3,4],[5,6,7],[3,45,55]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [38]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

a1.shape , a1.ndim , a1.dtype , type(a1)

((3,), 1, dtype('int64'), numpy.ndarray)

In [39]:
# Attributes of 2-dimensional array
a2.shape , a2.ndim , a2.dtype , type(a2)

((2, 3), 2, dtype('int64'), numpy.ndarray)

In [40]:
# Attributes of 3-dimensional array
a3.shape , a3.ndim , a3.dtype , type(a3)

((1, 3, 3), 3, dtype('int64'), numpy.ndarray)

In [41]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
df = pd.DataFrame(a2)
df

0   1  2
0  2   3  4
1  4  56  4

In [42]:
# Create an array of shape (10, 2) with only ones
ones= np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
# Create an array of shape (7, 2, 3) of only zeros
zero = np.zeros(shape= (7, 2, 3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
# Create an array within a range of 0 and 100 with step 3
range_array= np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [45]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand = np.random.randint(10,size=(7,2))
rand

array([[1, 4],
       [7, 9],
       [8, 8],
       [0, 8],
       [6, 8],
       [7, 0],
       [7, 7]], dtype=int32)

In [46]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_array= np.random.random((3,5))
rand_array



array([[0.01407982, 0.1988424 , 0.71134195, 0.79017554, 0.60595997],
       [0.92630088, 0.65107703, 0.91495968, 0.85003858, 0.44945067],
       [0.09541012, 0.37081825, 0.66884125, 0.66592236, 0.59129779]])

In [47]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand2 = np.random.randint(10,size=(4,6))
rand2


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [48]:
rand3

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]], dtype=int32)

In [35]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand3 = np.random.randint(1,10,size=(3,7))
rand3
# Find the unique numbers in the array you just created
np.unique(rand3)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [49]:
# Find the 0'th index of the latest array you created
rand3[0]

array([7, 8, 3, 1, 4, 2, 8], dtype=int32)

In [50]:
# Get the first 2 rows of latest array you created
rand3[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]], dtype=int32)

In [58]:
rand3

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]], dtype=int32)

In [60]:
# Get the first 2 values of the first 2 rows of the latest array
rand3[:2,:2]

array([[7, 8],
       [4, 2]], dtype=int32)

In [63]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand4 = np.random.randint(10,size=(3,5))
ones2 = np.ones(shape=(3,5))

In [69]:
# Add the two arrays together
x = rand4 + ones2
x

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

In [90]:
# Create another array of ones of shape (5, 3)
ones3 = np.ones(shape=(5,3))

In [83]:
# Try add the array of ones and the other most recent array together
x = rand4 + ones3
x

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [96]:
# Create another array of ones of shape (3, 5)
ones3 = ones3.reshape(3,5)
ones3.shape

(3, 5)

In [97]:
# Subtract the new array of ones from the other most recent array
rand4 - ones3

array([[ 7., -1.,  8.,  1.,  5.],
       [ 2.,  7.,  1.,  3.,  1.],
       [ 5.,  3.,  7.,  5.,  0.]])

In [98]:
# Multiply the ones array with the latest array
rand4*ones3

array([[8., 0., 9., 2., 6.],
       [3., 8., 2., 4., 2.],
       [6., 4., 8., 6., 1.]])

In [101]:
# Take the latest array to the power of 2 using '**'
rand4 ** ones3

array([[8., 0., 9., 2., 6.],
       [3., 8., 2., 4., 2.],
       [6., 4., 8., 6., 1.]])

In [102]:
# Do the same thing with np.square()
np.square(rand4)

array([[64,  0, 81,  4, 36],
       [ 9, 64,  4, 16,  4],
       [36, 16, 64, 36,  1]], dtype=int32)

In [103]:
# Find the mean of the latest array using np.mean()
np.mean(rand4)

np.float64(4.6)

In [105]:
# Find the maximum of the latest array using np.max()
np.max(rand4)

np.int32(9)

In [106]:
# Find the minimum of the latest array using np.min()
np.min(rand4)

np.int32(0)

In [107]:
# Find the standard deviation of the latest array
np.std(rand4)

np.float64(2.8000000000000003)

In [108]:
# Find the variance of the latest array
np.var(rand4)

np.float64(7.840000000000002)

In [109]:
# Reshape the latest array to (3, 5, 1)
rand4.reshape(3,5,1)

array([[[8],
        [0],
        [9],
        [2],
        [6]],

       [[3],
        [8],
        [2],
        [4],
        [2]],

       [[6],
        [4],
        [8],
        [6],
        [1]]], dtype=int32)

In [110]:
# Transpose the latest array
rand4.T

array([[8, 3, 6],
       [0, 8, 4],
       [9, 2, 8],
       [2, 4, 6],
       [6, 2, 1]], dtype=int32)

What does the transpose do?

In [111]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1 = np.random.randint(10,size=(3,3))
array2 = np.random.randint(10,size=(3,2))

In [112]:
# Perform a dot product on the two newest arrays you created
np.dot(array1,array2)

array([[ 97,  22],
       [153,  74],
       [ 79,  24]], dtype=int32)

In [113]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array1 = np.random.randint(10,size=(4,3))
array2 = np.random.randint(10,size=(4,3))

In [114]:
# Perform a dot product on the two newest arrays you created
np.dot(array1,array2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [115]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
array2=array2.T
np.dot(array1,array2)

array([[113, 113,  57,  32],
       [ 36,  49,  42,  30],
       [128, 135,  72,  50],
       [ 56,  68,  68,  24]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [116]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

array1 = np.random.randint(10,size=(4,3))
array2 = np.random.randint(10,size=(4,3))

In [117]:
# Compare the two arrays with '>'
array2>array1

array([[False, False, False],
       [False, False, False],
       [False,  True,  True],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

In [118]:
# Compare the two arrays with '>='
array1 >= array2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True, False]])

In [119]:
# Find which elements of the first array are greater than 7
array1 > 7

array([[ True, False,  True],
       [ True, False,  True],
       [False, False, False],
       [False, False, False]])

In [120]:
# Which parts of each array are equal? (try using '==')
array1 == array2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [121]:
# Sort one of the arrays you just created in ascending order
np.sort(array1)

array([[6, 9, 9],
       [6, 8, 8],
       [0, 1, 7],
       [6, 6, 7]], dtype=int32)

In [122]:
# Sort the indexes of one of the arrays you just created
np.argsort(array1)

array([[1, 0, 2],
       [1, 0, 2],
       [2, 1, 0],
       [0, 1, 2]])

In [123]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array1)

np.int64(0)

In [124]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array1)

np.int64(8)

In [127]:
array1

array([[9, 6, 9],
       [8, 6, 8],
       [7, 1, 0],
       [6, 6, 7]], dtype=int32)

In [126]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array1,axis=1)

array([0, 0, 0, 2])

In [128]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array1,axis=0)

array([3, 2, 2])

In [131]:
# Create an array of normally distributed random numbers
np.random.randn(4,5)

array([[ 2.28722598,  1.6229205 ,  0.82373308,  0.29305925,  0.89663038],
       [-0.61032202, -0.3161659 , -1.48242425, -0.22884752,  0.96264129],
       [-0.20969244, -0.77404293, -0.35977815,  0.72408325, -0.25576464],
       [ 0.8499212 , -1.31132423, -0.87030495, -0.50664322, -1.30995069]])

In [133]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.